### ISSUE TITLE
implemented the results for Y-net

### ISSUE THREAD

**Issue by SunshineDHW** [HRHLALALA/next-prediction-pytorch#2]
Hello,I noticed that you implemented the results for Y-net. I would like to know how to train and test on ETH/UCY datasets. They only provided Jupyter Notebook files for training and testing on the SSD dataset, without corresponding files for ETH/UCY. What should I do?
I would be greatly appreciative of your assistance. Thank you in advance.

**Comment by HRHLALALA** [comment]
Hi, I have tried to reproduce the results of YNet on ETH/UCY but unfortunately failed due to their unreasonable training time. Alternatively, you can check [Goal-SAR](https://github.com/luigifilippochiara/Goal-SAR/issues/2#issuecomment-1221469710) and follow their configurations. Note that I actually feel more reasonable to follow the experimental environment for Goal-SAR and you can easily migrate the model in YNet to Goal-SAR files. Also, do use some advanced graphic cards such as A100 to accelerate the training. Hope this helps.

**Comment by SunshineDHW** [comment]
Hello, thank you for your response! How long did it take for you to train on ETH/UCY? Is it significantly longer than training on SDD? Also, how did you obtain the train_ETH_trajnet.ipynb and the train_ETH_trajnet.yaml file ? Could you share those with me? Once again, sincere thanks for your help!

**Comment by HRHLALALA** [comment]
> Hello, thank you for your response! How long did it take for you to train on ETH/UCY? Is it significantly longer than training on SDD? Also, how did you obtain the train_ETH_trajnet.ipynb and the train_ETH_trajnet.yaml file ? Could you share those with me? Once again, sincere thanks for your help!

Yes, it is much longer (approximately 1 week on RTX3090). The training time using GoalSAR can be shorter (approx. 2 days).  I directly rewrote a `main.py` to accept all kinds of datasets and for ETH, I have only changed the `resize factor` to 0.666 and `segmentation_model_fp` to None. But as mentioned, GoalSAR is a better place to train on ETH/UCY. You can also migrate YNet to GoalSAR.
